name: 'setup-serverless'
description: 'A custom github action for setting up serverless-devs.'
author: 'yilun'

# Define your inputs here.
inputs:
  access_alias:
    description: 'Your access's alias.'
    required: true
    default: 'default'
  account_id:
    description: 'Account id, use "s config get {{access_alias}}" to check.'
    required: true
  access_key_id:
    description: 'Access key_id, use "s config get {{access_alias}}" to check.'
    required: true
  access_key_secret:
    description: 'Access key_secret, use "s config get {{access_alias}}" to check.'
    required: true

# Define your outputs here.
outputs:
  res:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
